config/routes.rb
# -*- encoding : utf-8 -*-
RestyAtp::Application.routes.draw do
  ActiveAdmin.routes(self)
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # join, login, logout
  match 'join' => 'users#join', :as => :join
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  # oauth
  resource :oauth do
    get :callback
  end
  match 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  # auth
  resources :user_sessions
  resources :password_resets
  #etc
  resources :users
  resources :themes do
    resources :pensions
  end
  resources :pensions do
    resources :reviews, :controller => :pension_reviews do
      get :detail, :on => :member
      put :helpful, :on => :member
    end
    resources :rooms
    get :update_like_count, :on => :collection
    get :update_comments_count, :on => :collection
    get :nearby, :on => :member
    get :map, :on => :member
    get :blog_posts, :on => :member
    get :pension_images, :on => :member
    get :outlink, :on => :member
  end
  resources :spots do
    resources :reviews, :controller => :spot_reviews
    resources :pensions
    get :map, :on => :member
  end
  resources :areas do
    resources :pensions
    resources :spots
    resources :sub_areas
  end
  resources :sub_areas do
    resources :spots
    resources :pensions
  end
  resources :spots
  resources :contacts
  #search
  match 'search/result' => 'search#result', :via => :post
  #api
  namespace :api do
    resources :pensions do
      get :blog_posts, :on => :member
    end
  end
  # main
  match 'main' => 'main#index'
  root :to => 'main#index'
end

app/models/spot.rb
# -*- encoding : utf-8 -*-
class Spot < ActiveRecord::Base
  has_many :spot_pensions
  has_many :pensions, :through => :spot_pensions
  has_many :reviews, :class_name => "SpotReview"
  belongs_to :area
  belongs_to :sub_area
  # validation
  validates_presence_of :title
  # geocode
  geocoded_by :addr
  after_validation :geocode, :if => :addr_changed?
  after_create :geocode
  # pension count
  after_validation :update_pensions_count, :if => :is_main
  
  default_scope order('pensions_count desc')
  scope :uncategorized, where('area_id = 0 or sub_area_id = 0')
  scope :main, reorder('rand()').limit(8)
  
  def sub_addr
    temp = addr.split(' ')
    if temp[1][-1] == '시' or temp[1][-1] == '군'
      temp[1][0..-2]
    else
      temp[0]
    end
  end
  
  def pensions
    Pension.near([self.latitude, self.longitude], 10, {:units => :km})
  end
    
  def near_by_pensions(limit=nil)
    if limit.nil?
      Pension.unscoped.near([self.latitude, self.longitude], 10, {:units => :km, :order => :distance})
    else
      Pension.unscoped.near([self.latitude, self.longitude], 10, {:units => :km, :order => :distance, :limit => limit})
    end
  end
  
  def html
    "<h3>#{self.title}</h3>
    <div><p><img src='/assets/address_icon.png'>&nbsp;#{self.addr}</p>
    <p><img src='/assets/phone_icon.png'>&nbsp;#{self.phone}</p>
    <p class='link'><a href='/spots/#{self.id}' target='_blank'>여행지 바로가기</a></p></div>"
  end
  
  private
  def update_pensions_count
    self.pensions_count = self.pensions.length
  end
end

app/controllers/spots_controller.rb
# -*- encoding : utf-8 -*-
class SpotsController < ApplicationController
  before_filter :store_location, :only => [:show]
  
  def index
    if !params[:sub_area_id].blank?
      @sub_area = SubArea.find(params[:sub_area_id])
      @area = @sub_area.area
      @spots = @sub_area.spots
    elsif !params[:area_id].blank?
      @area = Area.find(params[:area_id])
      @spots = @area.spots
    else
      @spots = Spot.all
    end
  end
  
  def show
    @spot = Spot.find(params[:id])
    @title = @spot.title
    @area = @spot.area
    @sub_area = @spot.sub_area
    @spots = @sub_area.spots
    @reviews = @spot.reviews.page(params[:page]).per(5)
    @near_by_pensions = @spot.near_by_pensions(5)
    @pensions = @near_by_pensions[0...10]
    @markers = [{:latitude => @spot.latitude, :longitude => @spot.longitude}].to_json
    @coupons = Coupon.ing.order('rand()').limit(5)
    @reviews = @spot.reviews.page(1).per(5)
  end
  
  def update_like_count
    @spot = Spot.find(params[:id])
    if params[:remove]
      @spot.decrement! :like_count
    else
      @spot.increment! :like_count
    end
    render :json => @spot.like_count
  end
  
  def update_comments_count
    @spot = Spot.find(params[:id])
    if params[:remove]
      @spot.decrement! :comments_count
    else
      @spot.increment! :comments_count
    end
    render :json => @spot.comments_count
  end
end

app/helpers/spots_helper.rb
# -*- encoding : utf-8 -*-
module SpotsHelper
end

app/views/spots/_header.mobile.erb
<div id="spot-nav" class="ui-bar">
  <%= form_tag spots_path, :method => :get, 'data-ajax' => false do %>
    <%= select_tag 'area_id', options_from_collection_for_select(Area.all, 'id', 'title', @area ? @area.id : ''), :prompt => @area ? '전체' : '지역', :onchange => "$('#sub_area_id').val('');$('#spot-nav form').submit()" %>
    <%= select_tag 'sub_area_id', options_from_collection_for_select(@area.sub_areas, 'id', 'title', @sub_area ? @sub_area.id : ''), :prompt => @sub_area ? '전체' : '지역', :onchange => "$('#spot-nav form').submit()" if @area %>
	<% end %>
</div>
<hr class="green">

app/views/spots/_pension_list.html.erb
<div class="sort">
  <span class="more-pensions"><%= link_to "#{@spot.title} 주변 펜션 더보기...", spot_pensions_path(@spot) %></span>
</div>

<div class="list">
<% @pensions.each do |pension| %>
  <div id="pension-<%= pension.id %>" class="pension-item">
  	<div class="line-dotted"></div>
  	<div class="left">
  	  <%= content_tag :span, 'must-visit-mark', :class => 'must-visit-mark' if params[:must_visit] or pension.must_visit %>
      <%= content_tag :span, "#{pension.coupon.disrate}%", :class => 'discount-mark' if pension.coupon %>
  		<div class="pension-thumbnail">
  		  <%= link_to image_tag(pension.list_img), pension %>
  		</div>
  		<div class="pension-info">
        <div class="pension-name">
          <%= link_to pension.title, pension %>
          <% if pension.like_count > 0 %>
            <span class="fb_like"><%= image_tag('like_resty.png', :width => '20px') %> <%= pension.like_count %></span>
          <% end %>
        </div>
        <% unless pension.roomstructure.blank? %>
          <div class="pension-type"><strong>용도:</strong> <%= pension.roomstructure %></div>
        <% end %>
        <% if pension.themes.count > 0 %>
          <div class="pension-theme">
            <% pension.themes.each do |theme| %>
              <%= image_tag("theme_icon_#{theme.id}.png", :width => '25px', :title => theme.title) %>
            <% end %>
          </div>
        <% end %>
        <% unless pension.facilities.blank? %>
          <div class="pension-faci"><strong>시설:</strong> <%= pension.facilities %></div>
        <% end %>
  		</div>
  	</div>
  	<div class="right">
  		<div class="pension-addr" title="<%= pension.addr %>"><%= pension.short_addr %></div>
  		<div class="pension-price">
  		  <% if pension.min_price == 0 %>
  		    사이트 확인 가능
  		  <% else %>
  		    <%= number_with_delimiter(pension.min_price) %>원 ~ <%= number_with_delimiter(pension.max_price) %>원
  		  <% end %>
  		</div>
  		<div class="pension-review">
        <span class="pension-review-count"><%= pension.reviews_count %></span>
        <span class="review-btn"><%= link_to '리뷰/후기', pension_path(pension) + "#show-review" %></span>
        <span class="detail-btn"><%= link_to '상세보기', pension %></span>
      </div>
  	</div>
  </div>
<% end %>
</div>
<div class="line-dotted"></div>

app/views/spots/index.mobile.erb
<%= render 'header' %>
<%= render 'spot_list' %>

app/views/spots/show.html.erb
<% content_for :og_meta do  %>
  <meta property="fb:app_id"      content="267286263291604">
  <meta property="og:type"        content="resty_atp:spot">
  <meta property="og:url"         content="http://www.resty.co.kr/spots/<%= @spot.id %>">
  <meta property="og:title"       content="<%= @spot.title %>">
  <meta property="og:description" content="<%= @spot.addr %>">
  <meta property="og:image"       content="http://www.resty.co.kr/logo.gif">
<% end %>

<div id="sidebar">
  <%= render 'show_sidebar' %>
</div>

<div id="main_content">
  <div class="header">
    <%= render 'header' %>
    <%#= link_to image_tag('review_event_banner_1.png', :id => 'banner'), '/assets/review_event_popup.png', :class => 'colorbox' %>
  </div>
  <div id="show-content">
    <div class="title">
      <h2><%= @spot.title %></h2>
      <div class="fb-like" data-href="http://www.resty.co.kr/spots/<%= @spot.id %>" data-send="false" data-layout="button_count" data-width="120" data-show-faces="false"></div>
    </div>
    <hr class="line-green">
    <div class="body">
      <div id="spot-info-sum"><%= @spot.description %><p>출처 : 한국관광공사</p></div>
      <div class="right">
        <div id="spot-info-addr"><%= @spot.addr %></div>
        <div id="spot-info-phone"><%= @spot.phone %></div>
        <div id="spot-info-url"><%= link_to truncate(@spot.url, :length => 50), @spot.url, :target => '_blank' %></div>
        <div id="spot-info-start">
          <div id="findway-box">
            <input type="text" value="<%= @spot.title %>까지의 길을 찾아드립니다." name="findway" id="findway-word" onclick="this.value='';" onkeypress="if(event.keyCode==13){$('#findway-button').trigger('click');}">
            <input type="image" value="" src="/assets/header_searchbox_button.png" id="findway-button" class="searchByAddress">
          </div>
        </div>
      </div>
      <div style="clear:both"></div>
    </div>
    <div id="show-footer">
	    <%= render 'map' %>
      <hr class="line-green">
    </div>
    <div id="show-review">
      <div id="spot-review-title"></div>
      <%#= render 'reviews/index' %>
      <fb:comments href="http://www.resty.co.kr/spots/<%= @spot.id %>" num-posts="5" width="709"></fb:comments>
      <script type="text/javascript" charset="utf-8">
        $(window).load(function() {
          FB.Event.subscribe('comment.create', function(response) {
            $.get('/spots/update_comments_count', {id:<%= @spot.id %>});
          });
          FB.Event.subscribe('comment.remove', function(response) {
            $.get('/spots/update_comments_count', {id:<%= @spot.id %>, remove:true});
          });
          FB.Event.subscribe('edge.create', function(response) {
            $.get('/spots/update_like_count', {id:<%= @spot.id %>});
          });
          FB.Event.subscribe('edge.remove', function(response) {
            $.get('/spots/update_like_count', {id:<%= @spot.id %>, remove:true});
          });
        });
      </script>
    </div>
  </div>
  <div id="pension-list">
    <%= render 'pension_list' %>
  </div>
</div>

app/views/spots/show.mobile.erb
<div id="show-info" data-role="collapsible" data-content-theme="c">
  <h3><%= @spot.title %> 소개</h3>
  <p><%= @spot.description %></p>
</div>
<table id="show-btn">
  <tbody>
    <tr>
      <td class="addr-btn"><%= link_to @spot.addr, "http://maps.google.com/maps?q=#{@spot.addr}@#{@spot.latitude},#{@spot.longitude}", 'data-role' => 'button' %></td>
      <td class="phone-btn"><%= link_to raw("전화걸기<hr>#{@spot.phone}"), "tel:#{@spot.phone.gsub('-','') unless @spot.phone.blank?}", 'data-role' => 'button', 'data-theme' => 'r' %></td>
    </tr>
  </tbody>
</table>
<div class="ui-bar">
  <h4 class="ui-left"><%= @spot.title %> 인근 펜션</h4>
  <%= link_to '더보기', spot_pensions_path(@spot), 'data-icon' => 'home', :class => 'ui-right' %>
</div>
<hr class="green">
<%= render 'pension_list' %>