config/routes.rb
# -*- encoding : utf-8 -*-
RestyAtp::Application.routes.draw do
  ActiveAdmin.routes(self)
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # join, login, logout
  match 'join' => 'users#join', :as => :join
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  # oauth
  resource :oauth do
    get :callback
  end
  match 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  # auth
  resources :user_sessions
  resources :password_resets
  #etc
  resources :users
  resources :themes do
    resources :pensions
  end
  resources :pensions do
    resources :reviews, :controller => :pension_reviews do
      get :detail, :on => :member
      put :helpful, :on => :member
    end
    resources :rooms
    get :update_like_count, :on => :collection
    get :update_comments_count, :on => :collection
    get :nearby, :on => :member
    get :map, :on => :member
    get :blog_posts, :on => :member
    get :pension_images, :on => :member
    get :outlink, :on => :member
  end
  resources :spots do
    resources :reviews, :controller => :spot_reviews
    resources :pensions
    get :map, :on => :member
  end
  resources :areas do
    resources :pensions
    resources :spots
    resources :sub_areas
  end
  resources :sub_areas do
    resources :spots
    resources :pensions
  end
  resources :spots
  resources :contacts
  #search
  match 'search/result' => 'search#result', :via => :post
  #api
  namespace :api do
    resources :pensions do
      get :blog_posts, :on => :member
    end
  end
  # main
  match 'main' => 'main#index'
  root :to => 'main#index'
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation, :providers_attributes
  
  has_many :providers, :class_name => 'UserProvider', :dependent => :destroy
  accepts_nested_attributes_for :providers
  
  authenticates_with_sorcery!
  
  validates_presence_of :email, :message => '이메일을 입력해 주세요.'
  validates_presence_of :gender, :message => '성별을 선택해 주세요.'
  validates_presence_of :age, :message => '나이를 선택해 주세요.'
  validates_presence_of :area, :message => '지역을 선택해 주세요.'
  validates_uniqueness_of :email, :unless => Proc.new {|user| user.external? }, :message => '이미 등록된 이메일입니다.'
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :message => '이메일 형식이 아닙니다.'
  validates_acceptance_of :term, :message => '이용약관에 동의해 주세요.'
  validates_acceptance_of :privacy, :message => '개인정보 수집 및 이용에 동의해 주세요.'
  validates_presence_of :password, :on => :create, :message => "비밀번호를 입력해 주세요."
  validates_length_of :password, :minimum => 3, :message => '비밀번호는 3자 이상 입력해 주세요.', :allow_blank => true
  validates_confirmation_of :password, :message => '비밀번호가 일치하지 않습니다.', :if => :password 
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :require_login, :except => [:join, :new, :create]
  skip_before_filter :user_info_check
  
  def join
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      auto_login @user
      redirect_to root_path, :notice => '회원 가입 완료!'
    else
      render :new
    end
  end
  
  # def show
  #   @user = User.find(params[:id])
  # end
  
  def edit
    @user = User.find(params[:id])
    redirect_to root_path, :notice => '잘못된 접근입니다.' unless @user == current_user
    @me = graph.get_object('me') if @user.providers.count == 1 and @user.gender.nil?
    if @me.present?
      if @me['gender'].present?
        @gender = @me['gender']
      end
      if @me['birthday'].present?
        @age = Time.new.year - @me['birthday'].split('/').last.to_i + 1
      end
      if @me['location'].present? and @me['location']['name'].present?
        @area = @me['location']['name'].split(' ').first
      end
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_path, :notice => '회원 정보 수정 완료!'
    else
      render :edit
    end
  end
  
  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy
  #   redirect_to root_path
  # end
  # 
  # def map
  # end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_menu.html.erb
<div id="mymenu-box">
	<h3 id="mymenu">MY MENU</h3>
	<ul>
	    <li><%= link_to 'my resty', @user %></li>
	    <li><%= link_to '나의 여행지도', map_user_path(@user) %></a></li>
	    <li><%= link_to '개인정보관리', edit_user_path(@user) %></li>
	</ul>
	<div class="box_footer"></div>
</div>

app/views/users/edit.html.erb
<div id="login-form">
  <h1 class="edit">resty 개인정보 변경</h1>
  <hr class="gray">
  <%= form_for @user, :html => {:method => :put} do |f| %>
  <table>
    <tr>
      <td class="align-center"><%= f.label :email, content_tag(:h3, '이메일') %></td>
      <td>
        <%= f.text_field :email, :class => 'text-input disabled', :disabled => true %>
      </td>
    </tr>
    <% if @user.providers.count == 0 %>
    <tr>
      <td class="align-center"><%= f.label :password, content_tag(:h3, '비밀번호') %></td>
      <td>
        <%= f.password_field :password, :class => 'text-input' %>
        <%= content_tag :p, @user.errors[:password][0], :class => 'form-error' if @user.errors[:password].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :password_confirmation, content_tag(:h3, '비밀번호확인') %></td>
      <td><%= f.password_field :password_confirmation, :class => 'text-input' %></td>
    </tr>
    <% end %>
    <tr>
      <td class="align-center"><%= f.label :gender, content_tag(:h3, '성별') %></td>
      <td>
        <% if @me.present? %>
          <%= f.radio_button :gender, 'M', :checked => (@gender.present? and @gender == 'male') %> 남
          &nbsp;&nbsp;&nbsp;
          <%= f.radio_button :gender, 'F', :checked => (@gender.present? and @gender == 'female') %> 여
        <% else %>
          <%= f.radio_button :gender, 'M' %> 남
          &nbsp;&nbsp;&nbsp;
          <%= f.radio_button :gender, 'F' %> 여
        <% end %>
        <%= content_tag :p, @user.errors[:gender][0], :class => 'form-error' if @user.errors[:gender].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :age, content_tag(:h3, '나이') %></td>
      <td>
        <% (10..60).step(10).each do |num| %>
          <% if @me.present? %>
            <%= f.radio_button :age, num, :checked => (@age.present? and @age / num == 1) %>
          <% else %>
            <%= f.radio_button :age, num %>
          <% end %>
          <%= "#{num}대" %>
          <%= num == 30 ? raw("<br>") : raw("&nbsp;&nbsp;&nbsp;") %>
        <% end %>
        <%= content_tag :p, @user.errors[:age][0], :class => 'form-error' if @user.errors[:age].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :area, content_tag(:h3, '사는지역') %></td>
      <td>
        <% if @me.present? %>
          <select id="user_area" name="user[area]">
            <option value="">지역</option>
            <% ['서울/인천/경기', '강원', '충북', '대전/충남', '전북', '광주/전남', '대구/경북', '부산/울산/경남', '제주'].each do |area| %>
              <option value="<%= area %>"<%= ' selected="selected"' unless @area.nil? or area.index(@area).nil? %>><%= area %></option>
            <% end %>
          </select>
        <% else %>
          <%= f.select :area, options_for_select(['서울/인천/경기', '강원', '충북', '대전/충남', '전북', '광주/전남', '대구/경북', '부산/울산/경남', '제주']) %>
        <% end %>
        <%= content_tag :p, @user.errors[:area][0], :class => 'form-error' if @user.errors[:area].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :email_agree, content_tag(:h3, '정보수신') %></td>
      <td>
        <%= f.radio_button :email_agree, true %> 예
        &nbsp;&nbsp;&nbsp;
        <%= f.radio_button :email_agree, false %> 아니오
      </td>
    </tr>
    <tr>
      <td colspan="2" class="align-right"><%= image_submit_tag "update_btn.png" %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/join.html.erb
<div id="login-form">
  <h1 class="join">resty 회원가입</h1>
  <hr class="gray">
  <table>
    <tr>
      <td class="join-fb"><%= image_tag 'fb_login_info.png' %></td>
      <td rowspan="2"><%= image_tag 'join_delimiter.png' %></td>
      <td class="join-resty"><%= image_tag 'resty_login_info.png' %></td>
    </tr>
    <tr>
      <td class="join-fb"><%= link_to image_tag('join_fb_btn.png'), auth_at_provider_path(:provider => :facebook) %></td>
      <td class="join-resty"><%= link_to image_tag('join_resty_btn.png'), new_user_path %></td>
    </tr>
  </table>
  <hr class="gray">
</div>

app/views/users/map.html.erb
<div id="sidebar">
  <%= render 'menu' %>
</div>

<div id="travel-map">
  <script src="../../assets/javascripts/sub.js" type="text/javascript"></script>
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAfYbrC3j-eC9_J5F_bZEEcxTSmgZntoPNWlO_PBdLIbBDSzXhaRSO6htZfBEKsO0rvyo52HPlz-fJOA" type="text/javascript"></script>
  <script src="../../assets/javascripts/jquery.gmap-1.1.0-min.js" type="text/javascript"></script>
  <script src="http://json-sans-eval.googlecode.com/svn/trunk/src/json_sans_eval.js" type="text/javascript"></script>

	<div id="my-travel-map">
		<div id="my-travel-map-title">
		  <h3>나의 여행지도</h3>
		  <div class="line_green"></div>
		</div>
		<div id="map"></div>
	  <div class="line_gray"></div>
    <div id="my-travel-map-list">
		    <ul>
        <li class="odd">
          <div class="date">2011년 8월 27일</div>
          <img src="../../assets/images/pension_01.jpg" alt="pension_01.jpg" title="1박2일 추월산펜션" />
          <div class="memo">1박2일 추월산펜션<br />진짜 좋아요~</div>
          <div class="address">전남 담양군 용면 월계리</div>
        </li>
        <li class="even">
          <div class="date">2011년 8월 27일</div>
          <img src="../../assets/images/pension_01.jpg" alt="pension_01.jpg" title="1박2일 추월산펜션" />
          <div class="memo">1박2일 추월산펜션<br />진짜 좋아요~</div>
          <div class="address">전남 담양군 용면 월계리</div>
        </li>
        <li class="odd">
          <div class="date">2011년 8월 27일</div>
          <img src="../../assets/images/pension_01.jpg" alt="pension_01.jpg" title="1박2일 추월산펜션" />
          <div class="memo">1박2일 추월산펜션<br />진짜 좋아요~</div>
          <div class="address">전남 담양군 용면 월계리</div>
        </li>
        <li class="even">
          <div class="date">2011년 8월 27일</div>
          <img src="../../assets/images/pension_01.jpg" alt="pension_01.jpg" title="1박2일 추월산펜션" />
          <div class="memo">1박2일 추월산펜션<br />진짜 좋아요~</div>
          <div class="address">전남 담양군 용면 월계리</div>
        </li>
        <li class="odd">
          <div class="date">2011년 8월 27일</div>
          <img src="../../assets/images/pension_01.jpg" alt="pension_01.jpg" title="1박2일 추월산펜션" />
          <div class="memo">1박2일 추월산펜션<br />진짜 좋아요~</div>
          <div class="address">전남 담양군 용면 월계리</div>
        </li>
      </ul>
	  </div>
	  <div class="line_gray"></div>
		<div id="my-travel-map-page">
		  <a href="#">1</a>
	    <span>2</span>
	    <a href="#">3</a>
	    <a href="#">4</a>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div id="login-form">
  <h1 class="join">resty 회원 가입</h1>
  <hr class="gray">
  <%= form_for @user do |f| %>
  <table>
    <tr>
      <td class="align-center"><%= f.label :email, content_tag(:h3, '이메일') %></td>
      <td>
        <%= f.text_field :email, :class => 'text-input' %>
        <%= content_tag :p, @user.errors[:email][0], :class => 'form-error' if @user.errors[:email].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :password, content_tag(:h3, '비밀번호') %></td>
      <td>
        <%= f.password_field :password, :class => 'text-input' %>
        <%= content_tag :p, @user.errors[:password][0], :class => 'form-error' if @user.errors[:password].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :password_confirmation, content_tag(:h3, '비밀번호확인') %></td>
      <td><%= f.password_field :password_confirmation, :class => 'text-input' %></td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :gender, content_tag(:h3, '성별') %></td>
      <td>
        <%= f.radio_button :gender, 'M' %> 남&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :gender, 'F' %> 여
        <%= content_tag :p, @user.errors[:gender][0], :class => 'form-error' if @user.errors[:gender].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :age, content_tag(:h3, '나이') %></td>
      <td>
        <% (10..60).step(10).each do |num| %>
          <%= f.radio_button :age, num %><%= "#{num}대" %>
          <%= num == 30 ? raw("<br>") : raw("&nbsp;&nbsp;&nbsp;") %>
        <% end %>
        <%= content_tag :p, @user.errors[:age][0], :class => 'form-error' if @user.errors[:age].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :area, content_tag(:h3, '사는지역') %></td>
      <td>
        <%= f.select :area, options_for_select([['지역', nil], '서울/경기', '강원', '충북', '대전/충남', '전북', '광주/전남', '대구/경북', '부산/경남', '제주']) %>
        <%= content_tag :p, @user.errors[:area][0], :class => 'form-error' if @user.errors[:area].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-center"><%= f.label :email_agree, content_tag(:h3, '정보수신') %></td>
      <td>
        <%= f.radio_button :email_agree, true %> 예
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.radio_button :email_agree, false %> 아니오
      </td>
    </tr>
    <tr>
      <td class="align-right" colspan="2">
        <%= f.check_box :term %>
        <%= f.label :term_accept, link_to('이용약관', page_path('terms'), :class => 'underline', :target => '_blank') + "에 동의합니다." %>
        <%= content_tag :p, @user.errors[:term][0], :class => 'form-error' if @user.errors[:term].present? %>
      </td>
    </tr>
    <tr>
      <td class="align-right" colspan="2">
        <%= f.check_box :privacy %>
        <%= f.label :privacy_accept, link_to('개인정보 수집 및 이용', page_path('privacy'), :class => 'underline', :target => '_blank') + "에 동의합니다." %>
        <%= content_tag :p, @user.errors[:privacy][0], :class => 'form-error' if @user.errors[:privacy].present? %>
      </td>
    </tr>
    <tr><td></td></tr>
    <tr>
      <td colspan="2" class="align-right">
        <%= image_submit_tag "join_submit_btn.png" %>
        <%= link_to image_tag('cancel_btn.png'), root_path %>
      </td>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="sidebar">
  <%= render 'menu' %>
</div>

<div id="myresty">
  <div id="favorite-resty">
		<div id="favorite-resty-title">
		    <h3>FAVORITE RESTY</h3>
		    <div class="category">
		    <a href="#">전체</a> | <a href="#">좋아요</a> | <a href="#">리뷰</a>
		    </div>
		    <div class="line_green"></div>
		</div>
		<div id="favorite-resty-list">
		    <ul>
		        <li class="odd">1박 2일 추월산펜션을 좋아합니다.</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="odd">1박 2일 추월산펜션을 좋아합니다.</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="odd">1박 2일 추월산펜션을 좋아합니다.</li>
		    </ul>
		    <div class="line_green"></div>
		</div>
		<div id="favorite-resty-page">
		    <a href="#">1</a>
		    <span>2</span>
		    <a href="#">3</a>
		    <a href="#">4</a>
		</div>
	</div>

	<div id="click-pension">
		<div id="click-pension-title">
		    <h3>FAVORITE RESTY</h3>
		    <div class="category">
		    <a href="#">전체</a> | <a href="#">좋아요</a> | <a href="#">리뷰</a>
		    </div>
		    <div class="line_green"></div>
		</div>
		<div id="click-pension-list">
		    <ul>
		        <li class="odd">2011년 8월 27일</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="even">1박 2일 추월산펜션을 좋아합니다.</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="even">1박 2일 추월산펜션을 좋아합니다.</li>
		    </ul>
		    <div class="line_gray"></div>
		    <ul>
		        <li class="odd">2011년 8월 23일</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="even">1박 2일 추월산펜션을 좋아합니다.</li>
		        <li class="even">1박 2일 추월산펜션을 리뷰했습니다.</li>
		        <li class="even">1박 2일 추월산펜션을 좋아합니다.</li>
		    </ul>
		    <div class="line_green"></div>
		</div>
		<div id="click-pension-page">
		    <a href="#">1</a>
		    <span>2</span>
		    <a href="#">3</a>
		    <a href="#">4</a>
		</div>
	</div>
</div>