config/routes.rb
# -*- encoding : utf-8 -*-
RestyAtp::Application.routes.draw do
  ActiveAdmin.routes(self)
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # join, login, logout
  match 'join' => 'users#join', :as => :join
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  # oauth
  resource :oauth do
    get :callback
  end
  match 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  # auth
  resources :user_sessions
  resources :password_resets
  #etc
  resources :users
  resources :themes do
    resources :pensions
  end
  resources :pensions do
    resources :reviews, :controller => :pension_reviews do
      get :detail, :on => :member
      put :helpful, :on => :member
    end
    resources :rooms
    get :update_like_count, :on => :collection
    get :update_comments_count, :on => :collection
    get :nearby, :on => :member
    get :map, :on => :member
    get :blog_posts, :on => :member
    get :pension_images, :on => :member
    get :outlink, :on => :member
  end
  resources :spots do
    resources :reviews, :controller => :spot_reviews
    resources :pensions
    get :map, :on => :member
  end
  resources :areas do
    resources :pensions
    resources :spots
    resources :sub_areas
  end
  resources :sub_areas do
    resources :spots
    resources :pensions
  end
  resources :spots
  resources :contacts
  #search
  match 'search/result' => 'search#result', :via => :post
  #api
  namespace :api do
    resources :pensions do
      get :blog_posts, :on => :member
    end
  end
  # main
  match 'main' => 'main#index'
  root :to => 'main#index'
end

app/models/pension.rb
# -*- encoding : utf-8 -*-
class Pension < ActiveRecord::Base
  has_many :reviews, :class_name => "PensionReview"
  has_many :rooms
  has_many :theme_pensions, :dependent => :destroy
  has_many :themes, :through => :theme_pensions
  has_many :logs, :class_name => "PensionLog"
  has_one :must_visit, :dependent => :destroy
  has_one :coupon, :dependent => :destroy, :conditions => ['is_valid = 1 and end_at > now()']
  belongs_to :area
  belongs_to :sub_area
  # facilities & roomstructure
  attr_accessor :facility_names
  after_validation :assign_facilities
  attr_accessor :roomstructure_names
  after_validation :assign_roomstructure
  # auto theme add
  after_update :auto_theme
  # price fix
  after_validation :price_fix
  # upload
  mount_uploader :thumbnail, PensionImageUploader
  mount_uploader :room_table, RoomTableUploader
  # geocode
  geocoded_by :addr
  after_validation :geocode, :if => :addr_changed?
  # scope
  default_scope order('ranking desc')
  1.upto 48 do |num|
    scope "task#{num}", where(:address02 => "task#{num}")
  end
  
  def near_by(limit=nil)
    if limit.nil?  
      Pension.unscoped.where("id <> ?", self.id).near(self, 10, {:units => :km, :order => :distance})
    else
      Pension.unscoped.where("id <> ?", self.id).near(self, 10, {:units => :km, :order => :distance, :limit => limit})
    end
  end
  
  def short_addr
    self.addr.split(' ')[0..2].join(' ')
  end
  
  def sub_addr
    temp = addr.split(' ')
    if temp[1][-1] == '시' or temp[1][-1] == '군'
      temp[1][0..-2]
    else
      temp[0]
    end
  end
  
  def list_img
    if self.thumbnail.url.index('http:/')
      'http://' + self.thumbnail.url.split('http:/')[1]
    else
      if Rails.env == "development"
        "http://www.resty.co.kr#{self.thumbnail.thumb.url}"
      else
        self.thumbnail.thumb.url
      end
    end
  end
  
  def show_img
    if self.thumbnail.url.index('http:/')
      'http://' + self.thumbnail.url.split('http:/')[1]
    else
      if Rails.env == "development"
        "http://www.resty.co.kr#{self.thumbnail.url}"
      else
        self.thumbnail.url
      end
    end
  end
  
  def og_img
    if self.thumbnail.url.index('http:/')
      'http://' + self.thumbnail.url.split('http:/')[1]
    else
      'http://www.resty.co.kr' + self.thumbnail.url
    end
  end
  
  def html
    "<h3>#{self.title}</h3>
    <img src='#{self.list_img}' class='thumbnail'>
    <div><p><img src='/assets/address_icon.png'>&nbsp;#{self.addr}</p>
    <p><img src='/assets/phone_icon.png'>&nbsp;#{self.mobile}</p>
    <p class='link'><a href='/pensions/#{self.id}' target='_blank'>펜션 바로가기</a></p></div>"
  end
  
  def html_list
    "<h3 style='margin-top: 0px'>#{self.title}</h3><a href='#pension-#{self.id}' onclick='highlight_pension(#{self.id})'>리스트로 바로가기</a>"
  end
    
  def facility_names
    if facilities.blank?
      temp = []
    else
      temp = facilities.split(',')
    end
    @facility_names || temp
  end
  
  def roomstructure_names
    if roomstructure.blank?
      temp = []
    else
      temp = roomstructure.split(',').collect {|x| x.strip}
    end
    @roomstrucutre_names || temp
  end
  
  def resty_url
    "http://www.resty.co.kr/pensions/#{self.id}"
  end
  
  private
  def assign_facilities
    if @facility_names
      @facility_names.delete('')
      self.facilities = @facility_names.join(',')
    end
  end
  
  def assign_roomstructure
    if @roomstructure_names
      @roomstructure_names.delete('')
      self.roomstructure = @roomstructure_names.join(',')
    end
  end
  
  def auto_theme
    unless roomstructure.blank?
      room_arr = roomstructure.split(',').collect {|x| x.strip}
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('커플').id, self.id if room_arr.include? '커플'
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('워크샵').id, self.id if room_arr.include? '워크샵'
    end
    unless facilities.blank?      
      facility_arr = facilities.split(',').collect {|x| x.strip}
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('스파/월풀').id, self.id if facility_arr.include? '스파/월풀'
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('수영장').id, self.id if facility_arr.include? '수영장'
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('카페').id, self.id if facility_arr.include? '카페'
      ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('자전거').id, self.id if facility_arr.include? '자전거'
    end
    ThemePension.find_or_create_by_theme_id_and_pension_id Theme.find_by_title('10만원이하').id, self.id if min_price <= 100000 and min_price > 0
  end
  
  def price_fix
    self.min_price = min_price * 10000 if !min_price.blank? and min_price < 1000
    self.max_price = max_price * 10000 if !max_price.blank? and max_price < 1000
  end
end

app/controllers/api/pensions_controller.rb
# -*- encoding : utf-8 -*-
class Api::PensionsController < ActionController::Base
  respond_to :json, :xml
  
  def index
    per = params[:per].present?? params[:per] : 10
    distance = params[:distance].present?? params[:distance] : 10
    if params[:spot_id].present?
      spot = Spot.find(params[:spot_id])
      point = [spot.latitude, spot.longitude]
      @pensions = Pension.near(point, distance, {:units => :km, :order => :distance})
    elsif params[:latitude].present? and params[:longitude].present?
      point = [params[:latitude].to_f, params[:longitude].to_f]
      @pensions = Pension.near(point, distance, {:units => :km, :order => :distance})
    else
      @pensions = Pension
    end
    @pensions = @pensions.page(params[:page]).per(per)
    respond_with(:total_page => @pensions.num_pages, :pensions => @pensions)
  end
  
  def show
    @pension = Pension.find(params[:id])
    respond_with(@pension)
  end
  
  def blog_posts
    per = params[:per].present?? params[:per] : 5
    @pension = Pension.find(params[:id])
    @sub_area = @pension.sub_area
    @blog_search = BlogSearch.new("#{@pension.sub_addr} #{@pension.title}", 20, "#{@sub_area.id}_#{@pension.id}")
    @blog_reviews = Kaminari::paginate_array(@blog_search.results).page(params[:page]).per(per)
    @posts = @blog_reviews.collect {|x| {:title => ActionController::Base.helpers.strip_tags(x.title), :link => x.link, :desc => ActionController::Base.helpers.strip_tags(x.desc)}}
    respond_with(:total_page => @blog_reviews.num_pages, :posts => @posts)
  end
end

app/controllers/pensions_controller.rb
# -*- encoding : utf-8 -*-
class PensionsController < ApplicationController
  def index
    # get area and spot
    if !params[:sub_area_id].blank?
      @sub_area = SubArea.find(params[:sub_area_id])
      @area = @sub_area.area
      @spots = @sub_area.spots
      @pensions = @sub_area.pensions
    elsif !params[:area_id].blank?
      @area = Area.find(params[:area_id])
      @spots = @area.spots
      @pensions = @area.pensions
    end
    # get spot
    if !params[:spot_id].blank?
      @spot = Spot.find(params[:spot_id])
      @sub_area = @spot.sub_area
      @area = @sub_area.area
      @spots = @sub_area.spots
      @pensions = @spot.pensions
    end
    # get pensions
    @pensions = Pension unless @pensions
    # get theme
    if !params[:theme_id].blank?
      @theme = Theme.find(params[:theme_id])
      @pensions = @pensions.joins(:theme_pensions).where('theme_pensions.theme_id' => @theme.id)
    end
    # get price
    if !params[:price_id].blank?
      @price = PriceRange.find(params[:price_id])
      if @price.max == 0
        @pensions = @pensions.where("min_price >= ?", @price.min)
      else
        @pensions = @pensions.where("min_price between ? and ?", @price.min, @price.max)
      end
      @pensions = @pensions.where("min_price <> 0")
    end
    # get facilities
    if !params[:facilities].blank?
      if params[:facilities].kind_of? Array
        @facilities = params[:facilities].map {|x| Facility.find(x)}
      else
        @facilities = params[:facilities].split(',').map {|x| Facility.find(x)}
      end
      like = @facilities.collect {|x| "facilities like '%#{x.title}%'"}.join(' and ')
      @pensions = @pensions.where(like)
    else
      @facilities = []
    end
    # must visit
    if params[:must_visit]
      @pensions = @pensions.joins(:must_visit)
    end
    # social commerce
    if params[:coupon]
      @pensions = @pensions.joins(:coupon).group("coupons.pension_id")
    end
    # order
    @total = @pensions.count
    @pensions = @pensions.reorder("#{params[:order_by]} desc") if params[:order_by]
    @pensions = @pensions.page(params[:page]).per(10)
    @markers = @pensions.collect {|x| {:latitude => x.latitude, :longitude => x.longitude, :html => x.html_list}}.to_json
  end
  
  def show
    @pension = Pension.find(params[:id])
    @title = @pension.title
    @area = @pension.area
    @sub_area = @pension.sub_area
    @near_by_pensions = @pension.near_by(5)
    @markers = [{:latitude => @pension.latitude, :longitude => @pension.longitude}].to_json
    @coupon = @pension.coupon
    @coupons = Coupon.ing.order('rand()').limit(5)
    @reviews = @pension.reviews.page(1).per(5)
    if mobile_device?
      @blog_search = BlogSearch.new("#{@pension.sub_addr} #{@pension.title}", 20, "#{@sub_area.id}_#{@pension.id}")
      @blog_reviews = Kaminari::paginate_array(@blog_search.results).page(params[:page]).per(5)
    end
  end
  
  def outlink
    @pension = Pension.find(params[:id])
    @title = @pension.title
    @log = PensionLog.find_or_create_by_pension_id_and_created_at_and_area_id_and_sub_area_id @pension.id, DateTime.current.to_date, @pension.area.id, @pension.sub_area.id
    @log.increment! :count
    render :layout => 'iframe'
  end
  
  def blog_posts
    @pension = Pension.find(params[:id])
    @sub_area = @pension.sub_area
    @blog_search = BlogSearch.new("#{@pension.sub_addr} #{@pension.title}", 20, "#{@sub_area.id}_#{@pension.id}")
    @blog_reviews = Kaminari::paginate_array(@blog_search.results).page(params[:page]).per(3)
  end
  
  def pension_images
    @pension = Pension.find(params[:id])
    @sub_area = @pension.sub_area
    @image_search = PensionImage.new("#{@pension.sub_addr} #{@pension.title}", 20, "#{@sub_area.id}_#{@pension.id}")
    @pension_images = Kaminari::paginate_array(@image_search.results).page(params[:page]).per(6)
  end
  
  def nearby
    @pension = Pension.find(params[:id])
    point = [@pension.latitude, @pension.longitude]
    @pensions = Pension.where('id <> ?', @pension.id).near(point, 10, {:units => :km, :order => :distance})
    @spots = Spot.near(point, 10, {:units => :km, :order => :distance})
    pension_markers = @pensions.collect {|x| {:key => "pension-#{x.id}", :latitude => x.latitude, :longitude => x.longitude, :html => x.html}}
    spot_markers = @spots.collect {|x| {:key => "spot-#{x.id}", :latitude => x.latitude, :longitude => x.longitude, :html => x.html, :icon => {:image => 'http://www.google.com/mapfiles/marker_green.png'}}}
    @results = (pension_markers + spot_markers).to_json
    render 'search/result'
  end
    
  def update_like_count
    @pension = Pension.find(params[:id])
    if params[:remove]
      @pension.decrement! :like_count
    else
      @pension.increment! :like_count
    end
    render :json => @pension.like_count
  end
  
  def update_comments_count
    @pension = Pension.find(params[:id])
    if params[:remove]
      @pension.decrement! :comments_count
    else
      @pension.increment! :comments_count
    end
    render :json => @pension.comments_count
  end
end

app/helpers/pensions_helper.rb
# -*- encoding : utf-8 -*-
module PensionsHelper
end

app/views/pensions/_blog_posts.html.erb
<div class="title">
  <%= paginate @blog_reviews, :params => {:action => 'blog_posts'}, :remote => true, :theme => 'ajax' %>
</div>
<hr class="gray">
<ul>
<% @blog_reviews.each do |item| %>
  <li>
    <b><%= link_to truncate(strip_tags(item.title), :length => 30), item.link, :target => :blank %></b>
    <p><%= strip_tags item.desc %></p>
  </li>
<% end %>
<% if @blog_reviews.count == 0 %>
  <li><p class="empty">수집된 블로그 리뷰가 없습니다.</p></li>
<% end %>
</ul>

app/views/pensions/_header.mobile.erb
<div id="pension-nav">
  <%= form_tag pensions_path, :method => :get, 'data-ajax' => false do %>
  <div class="ui-bar">
    <%= select_tag 'area_id', options_from_collection_for_select(Area.all, 'id', 'title', @area ? @area.id : ''), :prompt => @area ? '전체' : '지역', :onchange => "$('#sub_area_id').val('');$('#pension-nav form').submit()" %>
    <%= select_tag 'sub_area_id', options_from_collection_for_select(@area.sub_areas, 'id', 'title', @sub_area ? @sub_area.id : ''), :prompt => @sub_area ? '전체' : '지역', :onchange => "$('#pension-nav form').submit()" if @area %>
    <%= select_tag 'spot_id', options_from_collection_for_select(@spots, 'id', 'title', @spot ? @spot.id : ''), :prompt => @spot ? '전체' : '여행지', :onchange => "$('#pension-nav form').submit()" if @spots %>
  </div>
  <hr class="gray">
  <div class="ui-bar">
    <%= select_tag 'theme_id', options_from_collection_for_select(Theme.all, 'id', 'title', @theme ? @theme.id : ''), :prompt => @theme ? '전체' : '테마', :onchange => "$('#pension-nav form').submit()" %>
    <%= select_tag 'price_id', options_from_collection_for_select(PriceRange.order('min'), 'id', 'to_s', @price ? @price.id : ''), :prompt => @price ? '전체' : '가격대', :onchange => "$('#pension-nav form').submit()" %>
    <%= select_tag 'facilities', options_from_collection_for_select(Facility.all, 'id', 'title', params[:facilities] ? params[:facilities] : ''), :prompt => '시설', :multiple => true, 'data-native-menu' => false %>
  </div>
  <hr class="gray">
  <div class="ui-bar">
    <%= link_to 'Must Visit', params.merge(:must_visit => true), 'data-role' => 'button', 'data-inline' => 'true' unless params[:must_visit] %>
    <%= link_to 'Must Visit', params.merge(:must_visit => nil), 'data-role' => 'button', 'data-inline' => 'true', 'data-theme' => 'r' if params[:must_visit] %>
    <%= link_to '소셜커머스', params.merge(:coupon => true), 'data-role' => 'button', 'data-inline' => 'true' unless params[:coupon] %>
    <%= link_to '소셜커머스', params.merge(:coupon => nil), 'data-role' => 'button', 'data-inline' => 'true', 'data-theme' => 'r' if params[:coupon] %>
  </div>
  <% end %>
</div>
<hr class="green">

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('a[data-icon=delete]').live('click', function() {
      window.$('#pension-nav form').submit();
    });
  });
</script>

app/views/pensions/_list_sidebar.html.erb
<div class="themes_box">
  <h3 class="more hide">테마</h3>
  <ul>
    <% Theme.all.each_with_index do |theme, idx| %>
      <li class="<%= cycle('odd', 'even') %><%= ' toggle-list' if idx > 4 %>">
        <%= link_to_unless params[:theme_id].to_i == theme.id, theme.title, params.merge(:theme_id => theme.id, :page => nil) %>
      </li>
    <% end %>
  </ul>
  <div class="box_footer"></div>
</div>

<div class="prices_box">
  <h3>가격대</h3>
  <ul>
  <% PriceRange.order('min').each do |price| %>
    <li class="<%= cycle('odd', 'even') %>">
      <%= link_to_unless params[:price_id].to_i == price.id, price.to_s, params.merge(:price_id => price.id) %>
    </li>
  <% end %>
  </ul>
  <div class="box_footer"></div>
</div>

<div class="facilities_box">
  <h3 class="more hide">시설</h3>
  <ul>
  <% Facility.all.each_with_index do |facility, idx| %>
    <li class="<%= cycle('odd', 'even') %><%= ' toggle-list' if idx > 4 %>">
      <% if @facilities.include?(facility) %>
        <span class="checkbox checked">
          <%= link_to facility.title, remove_facility(facility.id) %>
        </span>
      <% else %>
        <span class="checkbox unchecked">
          <%= link_to facility.title, merge_facility(facility.id) %>
        </span>
      <% end %>
    </li>
  <% end %>
  </ul>
  <div class="box_footer"></div>
</div>
<div class="coupon-banner">
  <%= link_to image_tag('social_com_button.png', :alt => '펜션 소셜커머스'), pensions_path(params.merge(:coupon => true)) %>
</div>
<div class="must_visit_banner">
  <a href="<%= pensions_path(params.merge(:must_visit => true)) %>">
    <h3>Must Visit By Resty</h3>
    <%= image_tag('pension_01.jpg') %>
  </a>
</div>

app/views/pensions/show.html.erb
<% content_for :og_meta do  %>
  <meta property="fb:app_id"      content="267286263291604">
  <meta property="og:type"        content="resty_atp:pension">
  <meta property="og:url"         content="http://www.resty.co.kr/pensions/<%= @pension.id %>">
  <meta property="og:title"       content="<%= @pension.title %>">
  <meta property="og:description" content="<%= @pension.addr %>">
  <meta property="og:image"       content="<%= @pension.og_img %>">
<% end %>

<div id="sidebar">
  <%= render 'show_sidebar' %>
</div>

<div id="main_content">
  <div class="header">
    <%= render 'crumbs' %>
    <%#= link_to image_tag('review_event_banner_1.png', :id => 'banner'), '/assets/review_event_popup.png', :class => 'colorbox' %>
    <script type="text/javascript"><!--
    google_ad_client = "ca-pub-3538850815126610";
    /* 레스티 */
    google_ad_slot = "0834756091";
    google_ad_width = 705;
    google_ad_height = 90;
    //-->
    </script>
    <!--script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script-->
  </div>
  <div id="show-content">
    <div class="title">
      <h2><%= @pension.title %><span style="display:none"><%= @pension.title.gsub('펜션', '팬션') %></span></h2>
      <div class="fb-like" data-href="http://www.resty.co.kr/pensions/<%= @pension.id %>" data-send="false" data-layout="button_count" data-width="120" data-show-faces="false"></div>
    </div>
    <hr class="line-green">
    <div class="body">
      <div class="pension-photo">
        <%= link_to image_tag(@pension.show_img), outlink_pension_path(@pension), :target => '_blank' %>
      </div>
      <div class="pension-detail">
        <div id="pension-info-addr"><%= @pension.addr %></div>
        <div id="pension-info-type"><%= @pension.roomstructure %></div>
        <div id="pension-info-price">
          <% if @pension.min_price == 0 %>
            사이트 확인 가능
          <% else %>
            <%= @pension.min_price / 10000 %> ~ <%= @pension.max_price / 10000 %> 만원
          <% end %>
        </div>
        <div id="pension-info-faci"><%= @pension.facilities.split(',').join(', ') unless @pension.facilities.blank? %></div>
        <%= content_tag :div, "#{@pension.coupon.disrate}%", :class => 'discount-mark' if @coupon %>
        <div id="pension-info-theme"><%= @pension.themes.collect {|x| x.title}.join(', ') %></div>
        <div id="pension-info-url"><%= link_to truncate(@pension.url, :length => 50), outlink_pension_path(@pension), :target => '_blank' %></div>
        <div id="pension-info-start">
          <div id="findway-box">
            <input type="text" value="<%= @pension.title %>까지의 길을 찾아드립니다." name="findway" id="findway-word" onclick="this.value='';" onkeypress="if(event.keyCode==13){$('#findway-button').trigger('click');}">
            <input type="image" src="/assets/header_searchbox_button.png" id="findway-button" class="<%= 'searchByAddress' if @pension.longitude.blank? %><%= 'searchByGPS' unless @pension.longitude.blank? %>">
          </div>
        </div>
        <div id="info-gps-x"><%= @pension.longitude %></div>
        <div id="info-gps-y"><%= @pension.latitude %></div>
        <div id="pension-info-phone"><%= @pension.mobile or "사이트 확인 가능" %></div>
        <% unless @pension.room_table.blank? %>
          <%= link_to content_tag(:div, '', :id => 'pension-info-room'), @pension.room_table.url, :class => 'colorbox' %>
        <% end %>
      </div>
      <div style="clear:both;"></div>
    </div>
    
    <!-- 소셜 커머스 -->
    <% if @coupon %>
    <div id="coupon">
      <hr class="line-green">
      <div class="detail">
        <%= link_to image_tag(@coupon.image, :alt => '펜션 소셜커머스'), @coupon.link, :target => '_blank' %>
        <div class="info">
          <p><%= link_to @coupon.title, @coupon.link, :target => '_blank' %></p>
          <p class="date"><%= @coupon.start_at.to_date %> ~ <%= (@coupon.end_at-1).to_date %></p>
          <p class="price">
            <span class="org_price"><%= number_with_delimiter @coupon.org_price %>원</span>
            <span class="dis_price"><%= number_with_delimiter @coupon.dis_price %>원</span>
            <span class="provider"><%= @coupon.provider %> 진행중</span>
          </p>
        </div>
        <p class="clear"></p>
      </div>
      <hr class="line-green">
    </div>
    <% end %>

    <div id="show-footer">
  		<%= render 'map' %>
  		<hr class="line-green">
    </div>
    <div id="show-review"> 
      <%= render 'pension_reviews/index' %>
      <!-- <fb:comments href="http://www.resty.co.kr/pensions/<%= @pension.id %>" num-posts="5" width="709"></fb:comments> -->
      <script type="text/javascript" charset="utf-8">
        $(window).load(function() {
          FB.Event.subscribe('comment.create', function(response) {
            $.get('/pensions/update_comments_count', {id:<%= @pension.id %>});
          });
          FB.Event.subscribe('comment.remove', function(response) {
            $.get('/pensions/update_comments_count', {id:<%= @pension.id %>, remove:true});
          });
          FB.Event.subscribe('edge.create', function(response) {
            $.get('/pensions/update_like_count', {id:<%= @pension.id %>});
          });
          FB.Event.subscribe('edge.remove', function(response) {
            $.get('/pensions/update_like_count', {id:<%= @pension.id %>, remove:true});
          });
        });
      </script>
    </div>

    <div id="blog-review">
      <%= image_tag "ajax-loader.gif", :class => 'ajax-loader' %>
    </div>
    <div id="pension-image">
      <%= image_tag "ajax-loader.gif", :class => 'ajax-loader' %>
    </div>
    <script type="text/javascript" charset="utf-8">
      $.get("<%= blog_posts_pension_path(@pension) %>");
      $.get("<%= pension_images_pension_path(@pension) %>");
    </script>
  </div>
</div>

app/views/pensions/show.mobile.erb
<div class="align-center">
  <%= image_tag @pension.show_img, :class => 'show-img' %>
</div>
<div id="show-info" data-role="collapsible-set" data-theme="c" data-content-theme="d">
  <div data-role="collapsible" data-collapsed="false">
    <h3>시설</h3>
    <p><%= @pension.facilities.split(',').join(', ') unless @pension.facilities.blank? %></p>
  </div>
  <div data-role="collapsible">
    <h3>테마</h3>
    <p><%= @pension.themes.collect {|x| x.title}.join(', ') %></p>
  </div>
  <div data-role="collapsible">
    <h3>이용가격</h3>
    <p><%= @pension.min_price / 10000 %>만원 ~ <%= @pension.max_price / 10000%>만원</p>
  </div>
</div>
<% if @coupon %>
<div class="ui-bar">
  <h4><%= @coupon.provider %> 진행중</h4>
</div>
<ul data-role="listview" class="pension-list coupon-info">
  <hr class="green">
  <li>
    <a href="<%= @coupon.link %>" target="_blank">
      <%= image_tag @coupon.image, :class => 'pension-thumbnail' %>
      <%= content_tag :h3, @coupon.title %>
      <%= content_tag :p, "#{@coupon.start_at.to_date} ~ #{(@coupon.end_at-1).to_date}" %>
      <span class="org_price"><%= number_with_delimiter @coupon.org_price %>원</span>
      <span class="dis_price"><%= number_with_delimiter @coupon.dis_price %>원</span>
    </a>
  </li>
  <hr class="green">
</ul>
<% end %>
<table id="show-btn">
  <tbody>
    <tr>
      <td class="addr-btn"><%= link_to @pension.addr, "http://maps.google.com/maps?q=#{@pension.addr}@#{@pension.latitude},#{@pension.longitude}", 'data-role' => 'button' %></td>
      <td class="phone-btn"><%= link_to raw("전화걸기<hr>#{@pension.mobile}"), "tel:#{@pension.mobile.gsub('-','') unless @pension.mobile.blank?}", 'data-role' => 'button', 'data-theme' => 'r' %></td>
    </tr>
  </tbody>
</table>
<%= link_to '펜션 홈페이지 바로가기', @pension.url, 'data-role' => 'button', 'data-icon' => 'forward', :class => 'full-btn', :target => '_blank' %>
<div id="pension-blog">
  <div class="ui-bar">
    <h4 class="ui-left">블로그 이용후기</h4>
    <%= link_to '주변 펜션 더보기', nearby_pension_path(@pension), 'data-icon' => 'home', :class => 'green ui-right' %>
  </div>
  <hr class="green">
  <ul data-role="listview">
  <% @blog_reviews.each do |item| %>
    <li>
      <a href="<%= item.link %>" target="_blank">
        <h3><%= raw item.title %></h3>
        <p><%= raw item.desc %></p>
      </a>
    </li>
  <% end %>
  </ul>
  <%= paginate @blog_reviews %>
</div>