config/routes.rb
# -*- encoding : utf-8 -*-
RestyAtp::Application.routes.draw do
  ActiveAdmin.routes(self)
    
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # join, login, logout
  match 'join' => 'users#join', :as => :join
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  # oauth
  resource :oauth do
    get :callback
  end
  match 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  # auth
  resources :user_sessions
  resources :password_resets
  #etc
  resources :users
  resources :themes do
    resources :pensions
  end
  resources :pensions do
    resources :reviews, :controller => :pension_reviews do
      get :detail, :on => :member
      put :helpful, :on => :member
    end
    resources :rooms
    get :update_like_count, :on => :collection
    get :update_comments_count, :on => :collection
    get :nearby, :on => :member
    get :map, :on => :member
    get :blog_posts, :on => :member
    get :pension_images, :on => :member
    get :outlink, :on => :member
  end
  resources :spots do
    resources :reviews, :controller => :spot_reviews
    resources :pensions
    get :map, :on => :member
  end
  resources :areas do
    resources :pensions
    resources :spots
    resources :sub_areas
  end
  resources :sub_areas do
    resources :spots
    resources :pensions
  end
  resources :spots
  resources :contacts
  #search
  match 'search/result' => 'search#result', :via => :post
  #api
  namespace :api do
    resources :pensions do
      get :blog_posts, :on => :member
    end
  end
  # main
  match 'main' => 'main#index'
  root :to => 'main#index'
end

app/controllers/user_sessions_controller.rb
# -*- encoding : utf-8 -*-
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  skip_before_filter :user_info_check
  
  def new
  end
  
  def create
    session_backup = session[:return_to]
    user = login(params[:email], params[:password], params[:remember_me])
    session[:return_to] = session_backup
    if user
      redirect_after_login
    else
      flash[:alert] = "로그인에 실패 했습니다!"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => '로그아웃 되었습니다.'
  end
end

app/helpers/user_sessions_helper.rb
# -*- encoding : utf-8 -*-
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div id="login-form">
  <h1 class="login">resty 계정 로그인</h1>
  <hr class="gray">
  <div id="error_explanation">
    <%= alert %>
    <%= link_to '(비밀번호를 잃어버리셨습니까?)', '#', :onclick => "$('#reset-input').toggle();$('#login-input').toggle();" if flash[:alert].present? %>
  </div>
  <%= form_tag user_sessions_path, :id => 'login-input' do %>
    <table>
      <tr>
        <td class="align-center"><%= label_tag :email, content_tag(:h3, '이메일') %></td>
        <td><%= text_field_tag :email, params[:email], :class => 'text-input' %></td>
        <td>
          <%= check_box_tag :remember_me, 1, params[:remember_me] %>
          <%= label_tag :remember_me, '자동로그인' %>
        </td>
      </tr>
      <tr>
        <td class="align-center"><%= label_tag :password, content_tag(:h3, '비밀번호') %></td>
        <td><%= password_field_tag :password, nil, :class => 'text-input' %></td>
        <td><%= image_submit_tag "login_btn.png" %></td>
      </tr>
    </table>
  <% end %>
  <%= form_tag password_resets_path, :method => :post, :id => 'reset-input' do %>
    <table>
      <tr>
        <td><%= label_tag :email, content_tag(:h3, '이메일') %></td>
        <td><%= text_field_tag :email, params[:email], :class => 'text-input' %></td>
        <td><%= submit_tag '비밀번호 초기화' %></td>
      </tr>
    </table>
  <% end %>
  <div class="dot"></div>
  <ul id="btns">
    <li><%= link_to image_tag('fb_login_btn.png'), auth_at_provider_path(:provider => :facebook), :class => 'fb' %></li>
    <li><%= image_tag('btn_delimiter.png') %></li>
    <li><%= link_to image_tag('join_btn.png'), new_user_path %></li>
  </ul>
  <hr class="gray">
</div>

app/views/user_sessions/new.mobile.erb
<div class="align-center">
  <p class="alert"><%= alert %></p>
  <%= form_tag user_sessions_path, :id => 'login-input' do %>
    <div data-role="fieldcontain">
      <%= label_tag :email, '이메일' %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div data-role="fieldcontain">
      <%= label_tag :password, '비밀번호' %>
      <%= password_field_tag :password %>
    </div>
    <%= hidden_field_tag :remember_me, 1 %>
    <div class="ui-bar">
      <%= link_to '페이스북으로 로그인', auth_at_provider_path(:provider => :facebook), 'data-role' => 'button' %>
      <%= submit_tag '로그인' %>
    </div>
  <% end %>
</div>